import { IGithubRequest } from "../model/Request";
import { GithubBranchResponse, GithubCommitResponse, GithubIssueResponse, GithubRepositoryResponse, GithubUserResponse, IGithubResponse } from "../model/Response";
import { GithubTagResponse } from './../model/Response';

export abstract class GithubService {
  abstract fetchData(request: IGithubRequest): Array<IGithubResponse>;
};

export class GithubUserService extends GithubService {
  public fetchData(request: IGithubRequest): Array<GithubUserResponse> {
    const users: Array<GithubUserResponse> = [{
      login: "mojombo",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mojombo",
      "html_url": "https://github.com/mojombo",
      "followers_url": "https://api.github.com/users/mojombo/followers",
      "following_url": "https://api.github.com/users/mojombo/following{/other_user}",
      "gists_url": "https://api.github.com/users/mojombo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mojombo/subscriptions",
      "organizations_url": "https://api.github.com/users/mojombo/orgs",
      "repos_url": "https://api.github.com/users/mojombo/repos",
      "events_url": "https://api.github.com/users/mojombo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mojombo/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      login: "defunkt",
      "id": 2,
      "node_id": "MDQ6VXNlcjI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/defunkt",
      "html_url": "https://github.com/defunkt",
      "followers_url": "https://api.github.com/users/defunkt/followers",
      "following_url": "https://api.github.com/users/defunkt/following{/other_user}",
      "gists_url": "https://api.github.com/users/defunkt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/defunkt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/defunkt/subscriptions",
      "organizations_url": "https://api.github.com/users/defunkt/orgs",
      "repos_url": "https://api.github.com/users/defunkt/repos",
      "events_url": "https://api.github.com/users/defunkt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/defunkt/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      login: "pjhyett",
      "id": 3,
      "node_id": "MDQ6VXNlcjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pjhyett",
      "html_url": "https://github.com/pjhyett",
      "followers_url": "https://api.github.com/users/pjhyett/followers",
      "following_url": "https://api.github.com/users/pjhyett/following{/other_user}",
      "gists_url": "https://api.github.com/users/pjhyett/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pjhyett/subscriptions",
      "organizations_url": "https://api.github.com/users/pjhyett/orgs",
      "repos_url": "https://api.github.com/users/pjhyett/repos",
      "events_url": "https://api.github.com/users/pjhyett/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pjhyett/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      login: "wycats",
      "id": 4,
      "node_id": "MDQ6VXNlcjQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wycats",
      "html_url": "https://github.com/wycats",
      "followers_url": "https://api.github.com/users/wycats/followers",
      "following_url": "https://api.github.com/users/wycats/following{/other_user}",
      "gists_url": "https://api.github.com/users/wycats/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wycats/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wycats/subscriptions",
      "organizations_url": "https://api.github.com/users/wycats/orgs",
      "repos_url": "https://api.github.com/users/wycats/repos",
      "events_url": "https://api.github.com/users/wycats/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wycats/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      login: "ezmobius",
      "id": 5,
      "node_id": "MDQ6VXNlcjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ezmobius",
      "html_url": "https://github.com/ezmobius",
      "followers_url": "https://api.github.com/users/ezmobius/followers",
      "following_url": "https://api.github.com/users/ezmobius/following{/other_user}",
      "gists_url": "https://api.github.com/users/ezmobius/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ezmobius/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ezmobius/subscriptions",
      "organizations_url": "https://api.github.com/users/ezmobius/orgs",
      "repos_url": "https://api.github.com/users/ezmobius/repos",
      "events_url": "https://api.github.com/users/ezmobius/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ezmobius/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      login: "ivey",
      "id": 6,
      "node_id": "MDQ6VXNlcjY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivey",
      "html_url": "https://github.com/ivey",
      "followers_url": "https://api.github.com/users/ivey/followers",
      "following_url": "https://api.github.com/users/ivey/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivey/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivey/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivey/subscriptions",
      "organizations_url": "https://api.github.com/users/ivey/orgs",
      "repos_url": "https://api.github.com/users/ivey/repos",
      "events_url": "https://api.github.com/users/ivey/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivey/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      login: "evanphx",
      "id": 7,
      "node_id": "MDQ6VXNlcjc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/evanphx",
      "html_url": "https://github.com/evanphx",
      "followers_url": "https://api.github.com/users/evanphx/followers",
      "following_url": "https://api.github.com/users/evanphx/following{/other_user}",
      "gists_url": "https://api.github.com/users/evanphx/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/evanphx/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/evanphx/subscriptions",
      "organizations_url": "https://api.github.com/users/evanphx/orgs",
      "repos_url": "https://api.github.com/users/evanphx/repos",
      "events_url": "https://api.github.com/users/evanphx/events{/privacy}",
      "received_events_url": "https://api.github.com/users/evanphx/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      login: "vanpelt",
      "id": 17,
      "node_id": "MDQ6VXNlcjE3",
      "avatar_url": "https://avatars.githubusercontent.com/u/17?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vanpelt",
      "html_url": "https://github.com/vanpelt",
      "followers_url": "https://api.github.com/users/vanpelt/followers",
      "following_url": "https://api.github.com/users/vanpelt/following{/other_user}",
      "gists_url": "https://api.github.com/users/vanpelt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vanpelt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vanpelt/subscriptions",
      "organizations_url": "https://api.github.com/users/vanpelt/orgs",
      "repos_url": "https://api.github.com/users/vanpelt/repos",
      "events_url": "https://api.github.com/users/vanpelt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vanpelt/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      login: "wayneeseguin",
      "id": 18,
      "node_id": "MDQ6VXNlcjE4",
      "avatar_url": "https://avatars.githubusercontent.com/u/18?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wayneeseguin",
      "html_url": "https://github.com/wayneeseguin",
      "followers_url": "https://api.github.com/users/wayneeseguin/followers",
      "following_url": "https://api.github.com/users/wayneeseguin/following{/other_user}",
      "gists_url": "https://api.github.com/users/wayneeseguin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wayneeseguin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wayneeseguin/subscriptions",
      "organizations_url": "https://api.github.com/users/wayneeseguin/orgs",
      "repos_url": "https://api.github.com/users/wayneeseguin/repos",
      "events_url": "https://api.github.com/users/wayneeseguin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wayneeseguin/received_events",
      "type": "User",
      "site_admin": false
    }];

    return users;
  }
}

export class GithubRepoService extends GithubService {
  public fetchData(request: IGithubRequest): Array<GithubRepositoryResponse> {
    const repos: Array<GithubRepositoryResponse> = [{
      "id": 26899533,
      "node_id": "MDEwOlJlcG9zaXRvcnkyNjg5OTUzMw==",
      "name": "30daysoflaptops.github.io",
      "full_name": "mojombo/30daysoflaptops.github.io",
      "private": false,
      "owner": {
        "login": "mojombo",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mojombo",
        "html_url": "https://github.com/mojombo",
        "followers_url": "https://api.github.com/users/mojombo/followers",
        "following_url": "https://api.github.com/users/mojombo/following{/other_user}",
        "gists_url": "https://api.github.com/users/mojombo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mojombo/subscriptions",
        "organizations_url": "https://api.github.com/users/mojombo/orgs",
        "repos_url": "https://api.github.com/users/mojombo/repos",
        "events_url": "https://api.github.com/users/mojombo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mojombo/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/mojombo/30daysoflaptops.github.io",
      "description": null,
      "fork": false,
      "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io",
      "forks_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/forks",
      "keys_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/teams",
      "hooks_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/hooks",
      "issue_events_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/issues/events{/number}",
      "events_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/events",
      "assignees_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/assignees{/user}",
      "branches_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/branches{/branch}",
      "tags_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/tags",
      "blobs_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/languages",
      "stargazers_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/stargazers",
      "contributors_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/contributors",
      "subscribers_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/subscribers",
      "subscription_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/subscription",
      "commits_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/contents/{+path}",
      "compare_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/merges",
      "archive_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/downloads",
      "issues_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/issues{/number}",
      "pulls_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/labels{/name}",
      "releases_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/releases{/id}",
      "deployments_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/deployments",
      "created_at": new Date("2014-11-20T06:42:06Z"),
      "updated_at": new Date("2021-04-03T10:15:42Z"),
      "pushed_at": new Date("2014-11-20T06:42:47Z"),
      "git_url": "git://github.com/mojombo/30daysoflaptops.github.io.git",
      "ssh_url": "git@github.com:mojombo/30daysoflaptops.github.io.git",
      "clone_url": "https://github.com/mojombo/30daysoflaptops.github.io.git",
      "svn_url": "https://github.com/mojombo/30daysoflaptops.github.io",
      "homepage": null,
      "size": 1197,
      "stargazers_count": 7,
      "watchers_count": 7,
      "language": "CSS",
      "has_issues": false,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 2,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 2,
      "open_issues": 0,
      "watchers": 7,
      "default_branch": "gh-pages"
    },
    {
      "id": 17358646,
      "node_id": "MDEwOlJlcG9zaXRvcnkxNzM1ODY0Ng==",
      "name": "asteroids",
      "full_name": "mojombo/asteroids",
      "private": false,
      "owner": {
        "login": "mojombo",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mojombo",
        "html_url": "https://github.com/mojombo",
        "followers_url": "https://api.github.com/users/mojombo/followers",
        "following_url": "https://api.github.com/users/mojombo/following{/other_user}",
        "gists_url": "https://api.github.com/users/mojombo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mojombo/subscriptions",
        "organizations_url": "https://api.github.com/users/mojombo/orgs",
        "repos_url": "https://api.github.com/users/mojombo/repos",
        "events_url": "https://api.github.com/users/mojombo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mojombo/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/mojombo/asteroids",
      "description": "Destroy your Atom editor, Asteroids style!",
      "fork": false,
      "url": "https://api.github.com/repos/mojombo/asteroids",
      "forks_url": "https://api.github.com/repos/mojombo/asteroids/forks",
      "keys_url": "https://api.github.com/repos/mojombo/asteroids/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/mojombo/asteroids/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/mojombo/asteroids/teams",
      "hooks_url": "https://api.github.com/repos/mojombo/asteroids/hooks",
      "issue_events_url": "https://api.github.com/repos/mojombo/asteroids/issues/events{/number}",
      "events_url": "https://api.github.com/repos/mojombo/asteroids/events",
      "assignees_url": "https://api.github.com/repos/mojombo/asteroids/assignees{/user}",
      "branches_url": "https://api.github.com/repos/mojombo/asteroids/branches{/branch}",
      "tags_url": "https://api.github.com/repos/mojombo/asteroids/tags",
      "blobs_url": "https://api.github.com/repos/mojombo/asteroids/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/mojombo/asteroids/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/mojombo/asteroids/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/mojombo/asteroids/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/mojombo/asteroids/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/mojombo/asteroids/languages",
      "stargazers_url": "https://api.github.com/repos/mojombo/asteroids/stargazers",
      "contributors_url": "https://api.github.com/repos/mojombo/asteroids/contributors",
      "subscribers_url": "https://api.github.com/repos/mojombo/asteroids/subscribers",
      "subscription_url": "https://api.github.com/repos/mojombo/asteroids/subscription",
      "commits_url": "https://api.github.com/repos/mojombo/asteroids/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/mojombo/asteroids/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/mojombo/asteroids/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/mojombo/asteroids/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/mojombo/asteroids/contents/{+path}",
      "compare_url": "https://api.github.com/repos/mojombo/asteroids/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/mojombo/asteroids/merges",
      "archive_url": "https://api.github.com/repos/mojombo/asteroids/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/mojombo/asteroids/downloads",
      "issues_url": "https://api.github.com/repos/mojombo/asteroids/issues{/number}",
      "pulls_url": "https://api.github.com/repos/mojombo/asteroids/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/mojombo/asteroids/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/mojombo/asteroids/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/mojombo/asteroids/labels{/name}",
      "releases_url": "https://api.github.com/repos/mojombo/asteroids/releases{/id}",
      "deployments_url": "https://api.github.com/repos/mojombo/asteroids/deployments",
      "created_at": new Date("2014-03-03T07:40:00Z"),
      "updated_at": new Date("2021-12-20T18:13:50Z"),
      "pushed_at": new Date("2015-03-10T18:18:16Z"),
      "git_url": "git://github.com/mojombo/asteroids.git",
      "ssh_url": "git@github.com:mojombo/asteroids.git",
      "clone_url": "https://github.com/mojombo/asteroids.git",
      "svn_url": "https://github.com/mojombo/asteroids",
      "homepage": null,
      "size": 185,
      "stargazers_count": 94,
      "watchers_count": 94,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 13,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 3,
      "license": {
        "key": "other",
        "name": "Other",
        "spdx_id": "NOASSERTION",
        "url": null,
        "node_id": "MDc6TGljZW5zZTA="
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 13,
      "open_issues": 3,
      "watchers": 94,
      "default_branch": "master"
    },
    {
      "id": 29941343,
      "node_id": "MDEwOlJlcG9zaXRvcnkyOTk0MTM0Mw==",
      "name": "benbalter.github.com",
      "full_name": "mojombo/benbalter.github.com",
      "private": false,
      "owner": {
        "login": "mojombo",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mojombo",
        "html_url": "https://github.com/mojombo",
        "followers_url": "https://api.github.com/users/mojombo/followers",
        "following_url": "https://api.github.com/users/mojombo/following{/other_user}",
        "gists_url": "https://api.github.com/users/mojombo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mojombo/subscriptions",
        "organizations_url": "https://api.github.com/users/mojombo/orgs",
        "repos_url": "https://api.github.com/users/mojombo/repos",
        "events_url": "https://api.github.com/users/mojombo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mojombo/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/mojombo/benbalter.github.com",
      "description": "The personal website of Ben Balter. Built using Jekyll and GitHub Pages. See humans.txt for more infos.",
      "fork": true,
      "url": "https://api.github.com/repos/mojombo/benbalter.github.com",
      "forks_url": "https://api.github.com/repos/mojombo/benbalter.github.com/forks",
      "keys_url": "https://api.github.com/repos/mojombo/benbalter.github.com/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/mojombo/benbalter.github.com/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/mojombo/benbalter.github.com/teams",
      "hooks_url": "https://api.github.com/repos/mojombo/benbalter.github.com/hooks",
      "issue_events_url": "https://api.github.com/repos/mojombo/benbalter.github.com/issues/events{/number}",
      "events_url": "https://api.github.com/repos/mojombo/benbalter.github.com/events",
      "assignees_url": "https://api.github.com/repos/mojombo/benbalter.github.com/assignees{/user}",
      "branches_url": "https://api.github.com/repos/mojombo/benbalter.github.com/branches{/branch}",
      "tags_url": "https://api.github.com/repos/mojombo/benbalter.github.com/tags",
      "blobs_url": "https://api.github.com/repos/mojombo/benbalter.github.com/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/mojombo/benbalter.github.com/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/mojombo/benbalter.github.com/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/mojombo/benbalter.github.com/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/mojombo/benbalter.github.com/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/mojombo/benbalter.github.com/languages",
      "stargazers_url": "https://api.github.com/repos/mojombo/benbalter.github.com/stargazers",
      "contributors_url": "https://api.github.com/repos/mojombo/benbalter.github.com/contributors",
      "subscribers_url": "https://api.github.com/repos/mojombo/benbalter.github.com/subscribers",
      "subscription_url": "https://api.github.com/repos/mojombo/benbalter.github.com/subscription",
      "commits_url": "https://api.github.com/repos/mojombo/benbalter.github.com/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/mojombo/benbalter.github.com/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/mojombo/benbalter.github.com/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/mojombo/benbalter.github.com/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/mojombo/benbalter.github.com/contents/{+path}",
      "compare_url": "https://api.github.com/repos/mojombo/benbalter.github.com/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/mojombo/benbalter.github.com/merges",
      "archive_url": "https://api.github.com/repos/mojombo/benbalter.github.com/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/mojombo/benbalter.github.com/downloads",
      "issues_url": "https://api.github.com/repos/mojombo/benbalter.github.com/issues{/number}",
      "pulls_url": "https://api.github.com/repos/mojombo/benbalter.github.com/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/mojombo/benbalter.github.com/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/mojombo/benbalter.github.com/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/mojombo/benbalter.github.com/labels{/name}",
      "releases_url": "https://api.github.com/repos/mojombo/benbalter.github.com/releases{/id}",
      "deployments_url": "https://api.github.com/repos/mojombo/benbalter.github.com/deployments",
      "created_at": new Date("2015-01-27T23:54:05Z"),
      "updated_at": new Date("2021-01-13T19:44:45Z"),
      "pushed_at": new Date("2015-01-27T23:54:33Z"),
      "git_url": "git://github.com/mojombo/benbalter.github.com.git",
      "ssh_url": "git@github.com:mojombo/benbalter.github.com.git",
      "clone_url": "https://github.com/mojombo/benbalter.github.com.git",
      "svn_url": "https://github.com/mojombo/benbalter.github.com",
      "homepage": "http://ben.balter.com",
      "size": 20836,
      "stargazers_count": 5,
      "watchers_count": 5,
      "language": "CSS",
      "has_issues": false,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": false,
      "forks_count": 7,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 7,
      "open_issues": 0,
      "watchers": 5,
      "default_branch": "master"
    }, {
      "id": 4061,
      "node_id": "MDEwOlJlcG9zaXRvcnk0MDYx",
      "name": "auto_migrations",
      "full_name": "pjhyett/auto_migrations",
      "private": false,
      "owner": {
        "login": "pjhyett",
        "id": 3,
        "node_id": "MDQ6VXNlcjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pjhyett",
        "html_url": "https://github.com/pjhyett",
        "followers_url": "https://api.github.com/users/pjhyett/followers",
        "following_url": "https://api.github.com/users/pjhyett/following{/other_user}",
        "gists_url": "https://api.github.com/users/pjhyett/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pjhyett/subscriptions",
        "organizations_url": "https://api.github.com/users/pjhyett/orgs",
        "repos_url": "https://api.github.com/users/pjhyett/repos",
        "events_url": "https://api.github.com/users/pjhyett/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pjhyett/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/pjhyett/auto_migrations",
      "description": "Rails plugin for automating migrations",
      "fork": false,
      "url": "https://api.github.com/repos/pjhyett/auto_migrations",
      "forks_url": "https://api.github.com/repos/pjhyett/auto_migrations/forks",
      "keys_url": "https://api.github.com/repos/pjhyett/auto_migrations/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/pjhyett/auto_migrations/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/pjhyett/auto_migrations/teams",
      "hooks_url": "https://api.github.com/repos/pjhyett/auto_migrations/hooks",
      "issue_events_url": "https://api.github.com/repos/pjhyett/auto_migrations/issues/events{/number}",
      "events_url": "https://api.github.com/repos/pjhyett/auto_migrations/events",
      "assignees_url": "https://api.github.com/repos/pjhyett/auto_migrations/assignees{/user}",
      "branches_url": "https://api.github.com/repos/pjhyett/auto_migrations/branches{/branch}",
      "tags_url": "https://api.github.com/repos/pjhyett/auto_migrations/tags",
      "blobs_url": "https://api.github.com/repos/pjhyett/auto_migrations/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/pjhyett/auto_migrations/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/pjhyett/auto_migrations/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/pjhyett/auto_migrations/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/pjhyett/auto_migrations/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/pjhyett/auto_migrations/languages",
      "stargazers_url": "https://api.github.com/repos/pjhyett/auto_migrations/stargazers",
      "contributors_url": "https://api.github.com/repos/pjhyett/auto_migrations/contributors",
      "subscribers_url": "https://api.github.com/repos/pjhyett/auto_migrations/subscribers",
      "subscription_url": "https://api.github.com/repos/pjhyett/auto_migrations/subscription",
      "commits_url": "https://api.github.com/repos/pjhyett/auto_migrations/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/pjhyett/auto_migrations/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/pjhyett/auto_migrations/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/pjhyett/auto_migrations/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/pjhyett/auto_migrations/contents/{+path}",
      "compare_url": "https://api.github.com/repos/pjhyett/auto_migrations/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/pjhyett/auto_migrations/merges",
      "archive_url": "https://api.github.com/repos/pjhyett/auto_migrations/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/pjhyett/auto_migrations/downloads",
      "issues_url": "https://api.github.com/repos/pjhyett/auto_migrations/issues{/number}",
      "pulls_url": "https://api.github.com/repos/pjhyett/auto_migrations/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/pjhyett/auto_migrations/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/pjhyett/auto_migrations/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/pjhyett/auto_migrations/labels{/name}",
      "releases_url": "https://api.github.com/repos/pjhyett/auto_migrations/releases{/id}",
      "deployments_url": "https://api.github.com/repos/pjhyett/auto_migrations/deployments",
      "created_at": new Date("2008-03-16T00:44:24Z"),
      "updated_at": new Date("2021-04-17T04:46:31Z"),
      "pushed_at": new Date("2013-04-25T20:41:57Z"),
      "git_url": "git://github.com/pjhyett/auto_migrations.git",
      "ssh_url": "git@github.com:pjhyett/auto_migrations.git",
      "clone_url": "https://github.com/pjhyett/auto_migrations.git",
      "svn_url": "https://github.com/pjhyett/auto_migrations",
      "homepage": "http://errtheblog.com/posts/65-automatically",
      "size": 118,
      "stargazers_count": 147,
      "watchers_count": 147,
      "language": "Ruby",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": true,
      "forks_count": 44,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 1,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 44,
      "open_issues": 1,
      "watchers": 147,
      "default_branch": "master"
    },
    {
      "id": 112071,
      "node_id": "MDEwOlJlcG9zaXRvcnkxMTIwNzE=",
      "name": "blackjax",
      "full_name": "pjhyett/blackjax",
      "private": false,
      "owner": {
        "login": "pjhyett",
        "id": 3,
        "node_id": "MDQ6VXNlcjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pjhyett",
        "html_url": "https://github.com/pjhyett",
        "followers_url": "https://api.github.com/users/pjhyett/followers",
        "following_url": "https://api.github.com/users/pjhyett/following{/other_user}",
        "gists_url": "https://api.github.com/users/pjhyett/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pjhyett/subscriptions",
        "organizations_url": "https://api.github.com/users/pjhyett/orgs",
        "repos_url": "https://api.github.com/users/pjhyett/repos",
        "events_url": "https://api.github.com/users/pjhyett/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pjhyett/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/pjhyett/blackjax",
      "description": "buzzword-powered blackjack game",
      "fork": false,
      "url": "https://api.github.com/repos/pjhyett/blackjax",
      "forks_url": "https://api.github.com/repos/pjhyett/blackjax/forks",
      "keys_url": "https://api.github.com/repos/pjhyett/blackjax/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/pjhyett/blackjax/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/pjhyett/blackjax/teams",
      "hooks_url": "https://api.github.com/repos/pjhyett/blackjax/hooks",
      "issue_events_url": "https://api.github.com/repos/pjhyett/blackjax/issues/events{/number}",
      "events_url": "https://api.github.com/repos/pjhyett/blackjax/events",
      "assignees_url": "https://api.github.com/repos/pjhyett/blackjax/assignees{/user}",
      "branches_url": "https://api.github.com/repos/pjhyett/blackjax/branches{/branch}",
      "tags_url": "https://api.github.com/repos/pjhyett/blackjax/tags",
      "blobs_url": "https://api.github.com/repos/pjhyett/blackjax/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/pjhyett/blackjax/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/pjhyett/blackjax/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/pjhyett/blackjax/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/pjhyett/blackjax/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/pjhyett/blackjax/languages",
      "stargazers_url": "https://api.github.com/repos/pjhyett/blackjax/stargazers",
      "contributors_url": "https://api.github.com/repos/pjhyett/blackjax/contributors",
      "subscribers_url": "https://api.github.com/repos/pjhyett/blackjax/subscribers",
      "subscription_url": "https://api.github.com/repos/pjhyett/blackjax/subscription",
      "commits_url": "https://api.github.com/repos/pjhyett/blackjax/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/pjhyett/blackjax/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/pjhyett/blackjax/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/pjhyett/blackjax/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/pjhyett/blackjax/contents/{+path}",
      "compare_url": "https://api.github.com/repos/pjhyett/blackjax/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/pjhyett/blackjax/merges",
      "archive_url": "https://api.github.com/repos/pjhyett/blackjax/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/pjhyett/blackjax/downloads",
      "issues_url": "https://api.github.com/repos/pjhyett/blackjax/issues{/number}",
      "pulls_url": "https://api.github.com/repos/pjhyett/blackjax/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/pjhyett/blackjax/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/pjhyett/blackjax/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/pjhyett/blackjax/labels{/name}",
      "releases_url": "https://api.github.com/repos/pjhyett/blackjax/releases{/id}",
      "deployments_url": "https://api.github.com/repos/pjhyett/blackjax/deployments",
      "created_at": new Date("2009-01-21T20:45:27Z"),
      "updated_at": new Date("2021-02-21T06:39:54Z"),
      "pushed_at": new Date("2009-01-21T20:50:19Z"),
      "git_url": "git://github.com/pjhyett/blackjax.git",
      "ssh_url": "git@github.com:pjhyett/blackjax.git",
      "clone_url": "https://github.com/pjhyett/blackjax.git",
      "svn_url": "https://github.com/pjhyett/blackjax",
      "homepage": "",
      "size": 170,
      "stargazers_count": 10,
      "watchers_count": 10,
      "language": "Ruby",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 9,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 9,
      "open_issues": 0,
      "watchers": 10,
      "default_branch": "master"
    },
    {
      "id": 592,
      "node_id": "MDEwOlJlcG9zaXRvcnk1OTI=",
      "name": "errcount",
      "full_name": "pjhyett/errcount",
      "private": false,
      "owner": {
        "login": "pjhyett",
        "id": 3,
        "node_id": "MDQ6VXNlcjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pjhyett",
        "html_url": "https://github.com/pjhyett",
        "followers_url": "https://api.github.com/users/pjhyett/followers",
        "following_url": "https://api.github.com/users/pjhyett/following{/other_user}",
        "gists_url": "https://api.github.com/users/pjhyett/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pjhyett/subscriptions",
        "organizations_url": "https://api.github.com/users/pjhyett/orgs",
        "repos_url": "https://api.github.com/users/pjhyett/repos",
        "events_url": "https://api.github.com/users/pjhyett/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pjhyett/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/pjhyett/errcount",
      "description": "simple mongrel handler for a sweet hit counter",
      "fork": false,
      "url": "https://api.github.com/repos/pjhyett/errcount",
      "forks_url": "https://api.github.com/repos/pjhyett/errcount/forks",
      "keys_url": "https://api.github.com/repos/pjhyett/errcount/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/pjhyett/errcount/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/pjhyett/errcount/teams",
      "hooks_url": "https://api.github.com/repos/pjhyett/errcount/hooks",
      "issue_events_url": "https://api.github.com/repos/pjhyett/errcount/issues/events{/number}",
      "events_url": "https://api.github.com/repos/pjhyett/errcount/events",
      "assignees_url": "https://api.github.com/repos/pjhyett/errcount/assignees{/user}",
      "branches_url": "https://api.github.com/repos/pjhyett/errcount/branches{/branch}",
      "tags_url": "https://api.github.com/repos/pjhyett/errcount/tags",
      "blobs_url": "https://api.github.com/repos/pjhyett/errcount/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/pjhyett/errcount/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/pjhyett/errcount/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/pjhyett/errcount/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/pjhyett/errcount/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/pjhyett/errcount/languages",
      "stargazers_url": "https://api.github.com/repos/pjhyett/errcount/stargazers",
      "contributors_url": "https://api.github.com/repos/pjhyett/errcount/contributors",
      "subscribers_url": "https://api.github.com/repos/pjhyett/errcount/subscribers",
      "subscription_url": "https://api.github.com/repos/pjhyett/errcount/subscription",
      "commits_url": "https://api.github.com/repos/pjhyett/errcount/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/pjhyett/errcount/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/pjhyett/errcount/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/pjhyett/errcount/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/pjhyett/errcount/contents/{+path}",
      "compare_url": "https://api.github.com/repos/pjhyett/errcount/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/pjhyett/errcount/merges",
      "archive_url": "https://api.github.com/repos/pjhyett/errcount/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/pjhyett/errcount/downloads",
      "issues_url": "https://api.github.com/repos/pjhyett/errcount/issues{/number}",
      "pulls_url": "https://api.github.com/repos/pjhyett/errcount/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/pjhyett/errcount/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/pjhyett/errcount/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/pjhyett/errcount/labels{/name}",
      "releases_url": "https://api.github.com/repos/pjhyett/errcount/releases{/id}",
      "deployments_url": "https://api.github.com/repos/pjhyett/errcount/deployments",
      "created_at": new Date("2008-02-15T21:07:30Z"),
      "updated_at": new Date("2021-07-13T19:20:59Z"),
      "pushed_at": new Date("2008-03-26T19:15:12Z"),
      "git_url": "git://github.com/pjhyett/errcount.git",
      "ssh_url": "git@github.com:pjhyett/errcount.git",
      "clone_url": "https://github.com/pjhyett/errcount.git",
      "svn_url": "https://github.com/pjhyett/errcount",
      "homepage": "",
      "size": 109,
      "stargazers_count": 9,
      "watchers_count": 9,
      "language": "Ruby",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 9,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 2,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 9,
      "open_issues": 2,
      "watchers": 9,
      "default_branch": "master"
    }];

    return repos;
  }
}

export class GithubBranchService extends GithubService {
  public fetchData(request: IGithubRequest): Array<GithubBranchResponse> {
    const branches: Array<GithubBranchResponse> = [
      {
        "name": "gh-pages",
        "commit": {
          "sha": "52ea8096a319125a2118393894a421de7893d1d4",
          "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/commits/52ea8096a319125a2118393894a421de7893d1d4"
        },
        "protected": false
      },
      {
        "name": "master",
        "commit": {
          "sha": "a1edc8aae80b92497058ed7ffdde99ec2ea5efb4",
          "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/commits/a1edc8aae80b92497058ed7ffdde99ec2ea5efb4"
        },
        "protected": false
      },
      {
        "name": "patch-1",
        "commit": {
          "sha": "f06f5af6874ecd02c2ba7f52d9f6c48c9af14a2c",
          "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/commits/f06f5af6874ecd02c2ba7f52d9f6c48c9af14a2c"
        },
        "protected": false
      }
    ]

    return branches;
  }
}

export class GithubCommitService extends GithubService {
  public fetchData(request: IGithubRequest): Array<GithubCommitResponse> {
    const commits: Array<GithubCommitResponse> = [
      {
        "sha": "52ea8096a319125a2118393894a421de7893d1d4",
        "node_id": "MDY6Q29tbWl0MjY4OTk1MzM6NTJlYTgwOTZhMzE5MTI1YTIxMTgzOTM4OTRhNDIxZGU3ODkzZDFkNA==",
        "commit": {
          "author": {
            "name": "Alex Okolish",
            "email": "alex.okolish@gmail.com",
            "date": new Date("2014-11-20T05:51:19Z")
          },
          "committer": {
            "name": "Alex Okolish",
            "email": "alex.okolish@gmail.com",
            "date": new Date("2014-11-20T05:51:19Z")
          },
          "message": "small fix",
          "tree": {
            "sha": "b269cf24fd04e9d6fcccb72ec6a14a1ee253152d",
            "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/trees/b269cf24fd04e9d6fcccb72ec6a14a1ee253152d"
          },
          "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/commits/52ea8096a319125a2118393894a421de7893d1d4",
          "comment_count": 0,
          "verification": {
            "verified": false,
            "reason": "unsigned",
            "signature": null,
            "payload": null
          }
        },
        "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/commits/52ea8096a319125a2118393894a421de7893d1d4",
        "html_url": "https://github.com/mojombo/30daysoflaptops.github.io/commit/52ea8096a319125a2118393894a421de7893d1d4",
        "comments_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/commits/52ea8096a319125a2118393894a421de7893d1d4/comments",
        "author": {
          "login": "aokolish",
          "id": 705514,
          "node_id": "MDQ6VXNlcjcwNTUxNA==",
          "avatar_url": "https://avatars.githubusercontent.com/u/705514?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/aokolish",
          "html_url": "https://github.com/aokolish",
          "followers_url": "https://api.github.com/users/aokolish/followers",
          "following_url": "https://api.github.com/users/aokolish/following{/other_user}",
          "gists_url": "https://api.github.com/users/aokolish/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/aokolish/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/aokolish/subscriptions",
          "organizations_url": "https://api.github.com/users/aokolish/orgs",
          "repos_url": "https://api.github.com/users/aokolish/repos",
          "events_url": "https://api.github.com/users/aokolish/events{/privacy}",
          "received_events_url": "https://api.github.com/users/aokolish/received_events",
          "type": "User",
          "site_admin": false
        },
        "committer": {
          "login": "aokolish",
          "id": 705514,
          "node_id": "MDQ6VXNlcjcwNTUxNA==",
          "avatar_url": "https://avatars.githubusercontent.com/u/705514?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/aokolish",
          "html_url": "https://github.com/aokolish",
          "followers_url": "https://api.github.com/users/aokolish/followers",
          "following_url": "https://api.github.com/users/aokolish/following{/other_user}",
          "gists_url": "https://api.github.com/users/aokolish/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/aokolish/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/aokolish/subscriptions",
          "organizations_url": "https://api.github.com/users/aokolish/orgs",
          "repos_url": "https://api.github.com/users/aokolish/repos",
          "events_url": "https://api.github.com/users/aokolish/events{/privacy}",
          "received_events_url": "https://api.github.com/users/aokolish/received_events",
          "type": "User",
          "site_admin": false
        },
        "parents": [
          {
            "sha": "03e46e1677020f733a5c6b2e07594b5dfebed830",
            "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/commits/03e46e1677020f733a5c6b2e07594b5dfebed830",
            "html_url": "https://github.com/mojombo/30daysoflaptops.github.io/commit/03e46e1677020f733a5c6b2e07594b5dfebed830"
          }
        ]
      },
      {
        "sha": "03e46e1677020f733a5c6b2e07594b5dfebed830",
        "node_id": "MDY6Q29tbWl0MjY4OTk1MzM6MDNlNDZlMTY3NzAyMGY3MzNhNWM2YjJlMDc1OTRiNWRmZWJlZDgzMA==",
        "commit": {
          "author": {
            "name": "Alex Okolish",
            "email": "alex.okolish@gmail.com",
            "date": new Date("2014-11-20T05:33:15Z")
          },
          "committer": {
            "name": "Alex Okolish",
            "email": "alex.okolish@gmail.com",
            "date": new Date("2014-11-20T05:33:15Z")
          },
          "message": "first commit",
          "tree": {
            "sha": "38d175faf3e47192da90878c294dd40d773bdd2e",
            "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/trees/38d175faf3e47192da90878c294dd40d773bdd2e"
          },
          "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/git/commits/03e46e1677020f733a5c6b2e07594b5dfebed830",
          "comment_count": 0,
          "verification": {
            "verified": false,
            "reason": "unsigned",
            "signature": null,
            "payload": null
          }
        },
        "url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/commits/03e46e1677020f733a5c6b2e07594b5dfebed830",
        "html_url": "https://github.com/mojombo/30daysoflaptops.github.io/commit/03e46e1677020f733a5c6b2e07594b5dfebed830",
        "comments_url": "https://api.github.com/repos/mojombo/30daysoflaptops.github.io/commits/03e46e1677020f733a5c6b2e07594b5dfebed830/comments",
        "author": {
          "login": "aokolish",
          "id": 705514,
          "node_id": "MDQ6VXNlcjcwNTUxNA==",
          "avatar_url": "https://avatars.githubusercontent.com/u/705514?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/aokolish",
          "html_url": "https://github.com/aokolish",
          "followers_url": "https://api.github.com/users/aokolish/followers",
          "following_url": "https://api.github.com/users/aokolish/following{/other_user}",
          "gists_url": "https://api.github.com/users/aokolish/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/aokolish/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/aokolish/subscriptions",
          "organizations_url": "https://api.github.com/users/aokolish/orgs",
          "repos_url": "https://api.github.com/users/aokolish/repos",
          "events_url": "https://api.github.com/users/aokolish/events{/privacy}",
          "received_events_url": "https://api.github.com/users/aokolish/received_events",
          "type": "User",
          "site_admin": false
        },
        "committer": {
          "login": "aokolish",
          "id": 705514,
          "node_id": "MDQ6VXNlcjcwNTUxNA==",
          "avatar_url": "https://avatars.githubusercontent.com/u/705514?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/aokolish",
          "html_url": "https://github.com/aokolish",
          "followers_url": "https://api.github.com/users/aokolish/followers",
          "following_url": "https://api.github.com/users/aokolish/following{/other_user}",
          "gists_url": "https://api.github.com/users/aokolish/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/aokolish/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/aokolish/subscriptions",
          "organizations_url": "https://api.github.com/users/aokolish/orgs",
          "repos_url": "https://api.github.com/users/aokolish/repos",
          "events_url": "https://api.github.com/users/aokolish/events{/privacy}",
          "received_events_url": "https://api.github.com/users/aokolish/received_events",
          "type": "User",
          "site_admin": false
        },
        "parents": [

        ]
      }
    ]

    return commits;
  }
}

export class GithubIssueService extends GithubService {
  public fetchData(request: IGithubRequest): Array<GithubIssueResponse> {
    const issues: Array<GithubIssueResponse> = [
      {
        "url": "https://api.github.com/repos/octocat/Hello-World/issues/2184",
        "repository_url": "https://api.github.com/repos/octocat/Hello-World",
        "labels_url": "https://api.github.com/repos/octocat/Hello-World/issues/2184/labels{/name}",
        "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/2184/comments",
        "events_url": "https://api.github.com/repos/octocat/Hello-World/issues/2184/events",
        "html_url": "https://github.com/octocat/Hello-World/issues/2184",
        "id": 1139436878,
        "node_id": "I_kwDOABPHjc5D6m1O",
        "number": 2184,
        "title": "Hello, world!",
        "user": {
          "login": "today2204",
          "id": 35586127,
          "node_id": "MDQ6VXNlcjM1NTg2MTI3",
          "avatar_url": "https://avatars.githubusercontent.com/u/35586127?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/today2204",
          "html_url": "https://github.com/today2204",
          "followers_url": "https://api.github.com/users/today2204/followers",
          "following_url": "https://api.github.com/users/today2204/following{/other_user}",
          "gists_url": "https://api.github.com/users/today2204/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/today2204/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/today2204/subscriptions",
          "organizations_url": "https://api.github.com/users/today2204/orgs",
          "repos_url": "https://api.github.com/users/today2204/repos",
          "events_url": "https://api.github.com/users/today2204/events{/privacy}",
          "received_events_url": "https://api.github.com/users/today2204/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [

        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [

        ],
        "milestone": null,
        "comments": 0,
        "created_at": new Date("2022-02-16T02:10:55Z"),
        "updated_at": new Date("2022-02-16T02:10:55Z"),
        "closed_at": null,
        "author_association": "NONE",
        "active_lock_reason": null,
        "body": "I created this issue using Octokit!",
        "reactions": {
          "url": "https://api.github.com/repos/octocat/Hello-World/issues/2184/reactions",
          "total_count": 0,
          "laugh": 0,
          "hooray": 0,
          "confused": 0,
          "heart": 0,
          "rocket": 0,
          "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/octocat/Hello-World/issues/2184/timeline",
        "performed_via_github_app": null
      },
      {
        "url": "https://api.github.com/repos/octocat/Hello-World/issues/2180",
        "repository_url": "https://api.github.com/repos/octocat/Hello-World",
        "labels_url": "https://api.github.com/repos/octocat/Hello-World/issues/2180/labels{/name}",
        "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/2180/comments",
        "events_url": "https://api.github.com/repos/octocat/Hello-World/issues/2180/events",
        "html_url": "https://github.com/octocat/Hello-World/issues/2180",
        "id": 1139022076,
        "node_id": "I_kwDOABPHjc5D5Bj8",
        "number": 2180,
        "title": "Prueba timeline editado ✌️ ",
        "user": {
          "login": "CesarCobe",
          "id": 94635520,
          "node_id": "U_kgDOBaQGAA",
          "avatar_url": "https://avatars.githubusercontent.com/u/94635520?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/CesarCobe",
          "html_url": "https://github.com/CesarCobe",
          "followers_url": "https://api.github.com/users/CesarCobe/followers",
          "following_url": "https://api.github.com/users/CesarCobe/following{/other_user}",
          "gists_url": "https://api.github.com/users/CesarCobe/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/CesarCobe/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/CesarCobe/subscriptions",
          "organizations_url": "https://api.github.com/users/CesarCobe/orgs",
          "repos_url": "https://api.github.com/users/CesarCobe/repos",
          "events_url": "https://api.github.com/users/CesarCobe/events{/privacy}",
          "received_events_url": "https://api.github.com/users/CesarCobe/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [

        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [

        ],
        "milestone": null,
        "comments": 3,
        "created_at": new Date("2022-02-15T17:50:17Z"),
        "updated_at": new Date("2022-02-15T18:28:27Z"),
        "closed_at": null,
        "author_association": "NONE",
        "active_lock_reason": null,
        "body": null,
        "reactions": {
          "url": "https://api.github.com/repos/octocat/Hello-World/issues/2180/reactions",
          "total_count": 0,
          "laugh": 0,
          "hooray": 0,
          "confused": 0,
          "heart": 0,
          "rocket": 0,
          "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/octocat/Hello-World/issues/2180/timeline",
        "performed_via_github_app": null
      },
      {
        "url": "https://api.github.com/repos/octocat/Hello-World/issues/2179",
        "repository_url": "https://api.github.com/repos/octocat/Hello-World",
        "labels_url": "https://api.github.com/repos/octocat/Hello-World/issues/2179/labels{/name}",
        "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/2179/comments",
        "events_url": "https://api.github.com/repos/octocat/Hello-World/issues/2179/events",
        "html_url": "https://github.com/octocat/Hello-World/issues/2179",
        "id": 1138923551,
        "node_id": "I_kwDOABPHjc5D4pgf",
        "number": 2179,
        "title": "title",
        "user": {
          "login": "varun2948",
          "id": 37866666,
          "node_id": "MDQ6VXNlcjM3ODY2NjY2",
          "avatar_url": "https://avatars.githubusercontent.com/u/37866666?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/varun2948",
          "html_url": "https://github.com/varun2948",
          "followers_url": "https://api.github.com/users/varun2948/followers",
          "following_url": "https://api.github.com/users/varun2948/following{/other_user}",
          "gists_url": "https://api.github.com/users/varun2948/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/varun2948/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/varun2948/subscriptions",
          "organizations_url": "https://api.github.com/users/varun2948/orgs",
          "repos_url": "https://api.github.com/users/varun2948/repos",
          "events_url": "https://api.github.com/users/varun2948/events{/privacy}",
          "received_events_url": "https://api.github.com/users/varun2948/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [

        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [

        ],
        "milestone": null,
        "comments": 0,
        "created_at": new Date("2022-02-15T16:29:00Z"),
        "updated_at": new Date("2022-02-15T16:29:00Z"),
        "closed_at": null,
        "author_association": "NONE",
        "active_lock_reason": null,
        "body": null,
        "reactions": {
          "url": "https://api.github.com/repos/octocat/Hello-World/issues/2179/reactions",
          "total_count": 0,
          "laugh": 0,
          "hooray": 0,
          "confused": 0,
          "heart": 0,
          "rocket": 0,
          "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/octocat/Hello-World/issues/2179/timeline",
        "performed_via_github_app": null
      },
      {
        "url": "https://api.github.com/repos/octocat/Hello-World/issues/2177",
        "repository_url": "https://api.github.com/repos/octocat/Hello-World",
        "labels_url": "https://api.github.com/repos/octocat/Hello-World/issues/2177/labels{/name}",
        "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/2177/comments",
        "events_url": "https://api.github.com/repos/octocat/Hello-World/issues/2177/events",
        "html_url": "https://github.com/octocat/Hello-World/issues/2177",
        "id": 1138757336,
        "node_id": "I_kwDOABPHjc5D4A7Y",
        "number": 2177,
        "title": "How are you?",
        "user": {
          "login": "yanxiaonuo",
          "id": 33899039,
          "node_id": "MDQ6VXNlcjMzODk5MDM5",
          "avatar_url": "https://avatars.githubusercontent.com/u/33899039?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/yanxiaonuo",
          "html_url": "https://github.com/yanxiaonuo",
          "followers_url": "https://api.github.com/users/yanxiaonuo/followers",
          "following_url": "https://api.github.com/users/yanxiaonuo/following{/other_user}",
          "gists_url": "https://api.github.com/users/yanxiaonuo/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/yanxiaonuo/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/yanxiaonuo/subscriptions",
          "organizations_url": "https://api.github.com/users/yanxiaonuo/orgs",
          "repos_url": "https://api.github.com/users/yanxiaonuo/repos",
          "events_url": "https://api.github.com/users/yanxiaonuo/events{/privacy}",
          "received_events_url": "https://api.github.com/users/yanxiaonuo/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [

        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [

        ],
        "milestone": null,
        "comments": 1,
        "created_at": new Date("2022-02-15T14:19:19Z"),
        "updated_at": new Date("2022-02-15T14:19:20Z"),
        "closed_at": null,
        "author_association": "NONE",
        "active_lock_reason": null,
        "body": "this is a test",
        "reactions": {
          "url": "https://api.github.com/repos/octocat/Hello-World/issues/2177/reactions",
          "total_count": 0,
          "laugh": 0,
          "hooray": 0,
          "confused": 0,
          "heart": 0,
          "rocket": 0,
          "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/octocat/Hello-World/issues/2177/timeline",
        "performed_via_github_app": null
      }];

    return issues;
  }
}

export class GithubTagService extends GithubService {
  public fetchData(request: IGithubRequest): Array<GithubTagResponse> {
    const tags: Array<GithubTagResponse> = []

    return tags;
  }
}